title: Nagai Laboratory
description: Laboratory of Engineering for Maintenance System, Hokkaido University, Sapporo, Japan.
baseurl: "/skills-github-pages"
url: "https://nagailab2025.github.io"
theme: minima
